// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// integrate_test
void integrate_test();
RcppExport SEXP rddsigma_integrate_test() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    integrate_test();
    return R_NilValue;
END_RCPP
}
// integrate_test2
void integrate_test2(std::string method);
RcppExport SEXP rddsigma_integrate_test2(SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    integrate_test2(method);
    return R_NilValue;
END_RCPP
}
// integrate_test3
void integrate_test3();
RcppExport SEXP rddsigma_integrate_test3() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    integrate_test3();
    return R_NilValue;
END_RCPP
}
// tsgauss_lfunc_helper
double tsgauss_lfunc_helper(IntegerVector d, NumericVector w, double cutoff, NumericVector mu_u, double sd_u, double sigma);
RcppExport SEXP rddsigma_tsgauss_lfunc_helper(SEXP dSEXP, SEXP wSEXP, SEXP cutoffSEXP, SEXP mu_uSEXP, SEXP sd_uSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu_u(mu_uSEXP);
    Rcpp::traits::input_parameter< double >::type sd_u(sd_uSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(tsgauss_lfunc_helper(d, w, cutoff, mu_u, sd_u, sigma));
    return rcpp_result_gen;
END_RCPP
}
// tsgauss_lfunc_each_helper
NumericVector tsgauss_lfunc_each_helper(IntegerVector d, NumericVector w, double cutoff, NumericVector mu_u, double sd_u, double sigma);
RcppExport SEXP rddsigma_tsgauss_lfunc_each_helper(SEXP dSEXP, SEXP wSEXP, SEXP cutoffSEXP, SEXP mu_uSEXP, SEXP sd_uSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu_u(mu_uSEXP);
    Rcpp::traits::input_parameter< double >::type sd_u(sd_uSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(tsgauss_lfunc_each_helper(d, w, cutoff, mu_u, sd_u, sigma));
    return rcpp_result_gen;
END_RCPP
}
