# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

em_gauss_gauss_helper <- function(d_vec, w_vec, cutoff, tol, maxit, integ_method, integ_tol, integ_depth, verbose) {
    .Call('rddsigma_em_gauss_gauss_helper', PACKAGE = 'rddsigma', d_vec, w_vec, cutoff, tol, maxit, integ_method, integ_tol, integ_depth, verbose)
}

em_gauss_lap_helper <- function(d_vec, w_vec, cutoff, tol, maxit, integ_method, integ_tol, integ_depth, verbose) {
    .Call('rddsigma_em_gauss_lap_helper', PACKAGE = 'rddsigma', d_vec, w_vec, cutoff, tol, maxit, integ_method, integ_tol, integ_depth, verbose)
}

integrate_test <- function() {
    invisible(.Call('rddsigma_integrate_test', PACKAGE = 'rddsigma'))
}

integrate_test2 <- function(method, tol) {
    invisible(.Call('rddsigma_integrate_test2', PACKAGE = 'rddsigma', method, tol))
}

integrate_test3 <- function() {
    invisible(.Call('rddsigma_integrate_test3', PACKAGE = 'rddsigma'))
}

integrate_test4 <- function() {
    invisible(.Call('rddsigma_integrate_test4', PACKAGE = 'rddsigma'))
}

tsgauss_lfunc_helper <- function(d, w, cutoff, mu_u, sd_u, sigma) {
    .Call('rddsigma_tsgauss_lfunc_helper', PACKAGE = 'rddsigma', d, w, cutoff, mu_u, sd_u, sigma)
}

tsgauss_lfunc_each_helper <- function(d, w, cutoff, mu_u, sd_u, sigma) {
    .Call('rddsigma_tsgauss_lfunc_each_helper', PACKAGE = 'rddsigma', d, w, cutoff, mu_u, sd_u, sigma)
}

